# accounts-allowlist=["*"]

nodes-allowlist=[
    # node1.ozonechain.io
    "enode://ec251abbc828ca406971945d8e90ae319d5bb5d57b98b5448529d848f18b1305a0516c841a41143c55ff075eccba6a2c8658b8dbfd649fe310dba6cc922421e2@139.59.19.72:30303",

    # node2.ozonechain.io
    "enode://ed9fdb5f5a1e7b083483c5c4ef03d9ed5b46db1f35511f8732050ae6782db599d8230c495675b47f91ef2fc0c5787fab35b30c6c54ee5298bfc700c025311a2e@137.184.140.222:30303",

    # node3.ozonechain.io
    "enode://2b416112d60357d0829043b9b58623e0a98a0a631212291bc5d86e94f49ce1fd8ba8ba3c63c49e35acb473b13fc4f88530788fced5e1785680a8c27208799cff@146.190.224.244:30303",

    # node4.ozonechain.io
    "enode://a083da6a20a5bd77a7a489d24488abbddc2b5d859f167d76ea3f0ea04cced6ad94707e8e186d97c10573d0b41a858ccf0a0dd2ae06e578bad6bde5ea215b3898@159.65.134.195:30303"

    
]





  
